//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecetteCuisine
{
    using System;
    using System.Collections.Generic;

    public class Recipe
    {
        // Constructeur par défaut
        public Recipe()
        {
        }
        public Recipe(string name, string ingredients, string preparationSteps, int preparationTime, string photo, int userId)
        {
            Name = name;
            Ingredients = ingredients;
            PreparationSteps = preparationSteps;
            PreparationTime = preparationTime;
            Photo = photo;
            UserId = userId;
        }
        // Propriétés
        public int RecipeId { get; set; } // Clé primaire
        public string Name { get; set; } // Nom de la recette
        public string Ingredients { get; set; } // Liste des ingrédients
        public string PreparationSteps { get; set; } // Étapes de préparation
        public int PreparationTime { get; set; } // Temps de préparation en minutes
        public string Photo { get; set; } // URL ou chemin vers une photo facultative

        // Clé étrangère pour l'utilisateur
        public int UserId { get; set; }

        // Propriété de navigation pour Entity Framework
        // Assurez-vous que la classe User est également définie dans votre projet
        public virtual User User { get; set; }
    }

}
