//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace RecetteCuisine
{
    public class User
    {
        internal string PasswordHash;

        public User()
        {
            this.Recipes = new HashSet<Recipe>();
        }

        [Key]
        public int UserId { get; set; }

        [Required]
        [StringLength(50)]
        public string Username { get; set; }

        [Required]
        [StringLength(255)] // Assuming hashed passwords will be stored, which can be longer
        public string Password { get; set; }

        public virtual ICollection<Recipe> Recipes { get; set; }
    }
}

